[package]
name = "simple-tiled-wfc"
version = "0.6.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitsetium = "0.0.0"
rand = "0.7"